# This file was generated by nixos-generate-config on the target machine.
# To generate it on your machine, run:
#
#   sudo nixos-generate-config --show-hardware-config > hosts/nixos/hardware-configuration.nix
#
# Then commit it to your repo and rebuild.
#
# Do not manually edit this file — regenerate it if hardware changes significantly.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # Replace the contents of this file with the output of:
  #   sudo nixos-generate-config --show-hardware-config
}
